export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const CREATE_APPLICATION = 'CREATE_APPLICATION';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';